### ISSUE TITLE
settings in cookie

### ISSUE THREAD

**Issue by kng** [kmjonsson/morse_code_game#2]
Enable speed settings to be set in a cookie.
Also possible to save which tests (coloring?) have been completed with a accuracy above 90-95%.

**Comment by kmjonsson** [comment]
"Enable speed settings to be set in a cookie." are fixed.

**Comment by kmjonsson** [comment]
Define a test: Is the test of koch1 on 20wpm the same as 15wpm and is it the same with only 10 chars or does it need 50 or more?
